services:
  mysql:
    image: mysql:8.0
    container_name: employee-mysql

    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: employee_db

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  backend:
    build: ./backend
    container_name: employee-backend

    environment:
      DATABASE_URL: mysql+pymysql://root:1234@mysql:3306/employee_db

    ports:
      - "8000:8000"

    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: employee-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

volumes:
  mysql_data: